plugins {
    id 'java-library'
    id 'io.freefair.lombok' version '9.1.0'
    id 'io.qameta.allure' version '2.11.2'
}

repositories {
    mavenCentral()
}

def restAssuredVersion = "5.3.1"
def allureVersion = "2.21.0"

allure {
    report {
        version.set(allureVersion)
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}

dependencies {
    testImplementation(
            "org.slf4j:slf4j-simple:2.0.13",
            "org.junit.jupiter:junit-jupiter:5.10.0",
            "io.rest-assured:rest-assured:$restAssuredVersion",
            "org.hamcrest:hamcrest:3.0",
            "io.rest-assured:json-schema-validator:$restAssuredVersion",
            "io.qameta.allure:allure-rest-assured:$allureVersion"

    )
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperties(System.getProperties())

    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}

task advanced_test(type:Test) {
    useJUnitPlatform{
        includeTags("advanced")
    }
}